//! Small shared CLI helpers. Kept here so `main.rs` (status view), the
//! `init` wizard, and the `identity` command share one secret-masking and
//! prompt implementation instead of drifting.

use std::io::{self, BufRead, Write};
use std::path::Path;

use anyhow::{Context, Result};

/// Mask an API key / token for display: keep enough of the head and tail to
/// recognise it without leaking it into the terminal or scrollback. Short
/// values collapse to a placeholder so we never reveal a whole short secret.
pub fn mask_secret(value: &str) -> String {
    let trimmed = value.trim();
    if trimmed.len() <= 12 {
        return "<set>".to_string();
    }
    let head: String = trimmed.chars().take(8).collect();
    let tail: String = trimmed
        .chars()
        .rev()
        .take(4)
        .collect::<String>()
        .chars()
        .rev()
        .collect();
    format!("{head}…{tail}")
}

/// Render a secret for a status/summary line: `not set` when empty, otherwise
/// the masked form from [`mask_secret`].
pub fn secret_status(value: &str) -> String {
    if value.trim().is_empty() {
        "not set".to_string()
    } else {
        mask_secret(value)
    }
}

/// Print `prompt`, read one line from stdin, trim the trailing newline.
pub fn prompt_line(prompt: &str) -> Result<String> {
    print!("{prompt}");
    io::stdout().flush().ok();
    let stdin = io::stdin();
    let mut line = String::new();
    stdin
        .lock()
        .read_line(&mut line)
        .with_context(|| "reading stdin")?;
    Ok(line
        .trim_end_matches('\n')
        .trim_end_matches('\r')
        .to_string())
}

/// `[y/N]`-style confirmation. `default_yes` decides what an empty answer means.
pub fn confirm(prompt: &str, default_yes: bool) -> Result<bool> {
    let answer = prompt_line(prompt)?;
    let answer = answer.trim().to_ascii_lowercase();
    if answer.is_empty() {
        return Ok(default_yes);
    }
    Ok(answer.starts_with('y'))
}

/// Read a secret without echoing it. Falls back to a plain (echoed) read only
/// when no TTY is available for hidden input.
pub fn prompt_secret(prompt: &str) -> Result<String> {
    match rpassword::prompt_password(prompt) {
        Ok(value) => Ok(value),
        Err(_) => prompt_line(prompt),
    }
}

/// Read a multi-line block from stdin: collect lines until an empty line or
/// EOF. Returns `None` when nothing was entered. `hint` lines are printed
/// before reading.
pub fn read_multiline(hint: &[&str]) -> Result<Option<String>> {
    for line in hint {
        println!("{line}");
    }
    let mut lines: Vec<String> = Vec::new();
    let stdin = io::stdin();
    let mut handle = stdin.lock();
    loop {
        print!("  > ");
        io::stdout().flush().ok();
        let mut line = String::new();
        let read = handle
            .read_line(&mut line)
            .with_context(|| "reading stdin")?;
        if read == 0 {
            break; // EOF
        }
        let trimmed = line.trim_end_matches(['\n', '\r']);
        if trimmed.trim().is_empty() {
            break;
        }
        lines.push(trimmed.to_string());
    }
    let text = lines.join("\n").trim().to_string();
    Ok((!text.is_empty()).then_some(text))
}

/// Upsert `updates` into the `.env` at `path`, preserving every other line
/// (comments, blanks, and unmanaged keys). Creates the file with a header
/// when it doesn't exist. Locks the file to user-only `0600` — it holds API
/// secrets. Shared by `init` and `identity` so neither clobbers the other's
/// keys.
pub fn upsert_env(path: &Path, updates: &[(String, String)]) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating config dir at {}", parent.display()))?;
    }
    let stamp = chrono::Utc::now().format("%Y-%m-%d %H:%M:%S %Z");
    let existing = std::fs::read_to_string(path).unwrap_or_default();
    let had_content = !existing.trim().is_empty();

    let mut pending: std::collections::HashMap<&str, &str> = updates
        .iter()
        .map(|(k, v)| (k.as_str(), v.as_str()))
        .collect();
    let mut out: Vec<String> = Vec::new();

    if !had_content {
        out.push(format!(
            "# Lethe configuration — generated by `lethe init` on {stamp}"
        ));
        out.push(String::new());
    } else {
        for raw in existing.lines() {
            let trimmed = raw.trim_start();
            if !trimmed.is_empty()
                && !trimmed.starts_with('#')
                && let Some((key, _)) = trimmed.split_once('=')
                && let Some(value) = pending.remove(key.trim())
            {
                out.push(format!("{}={value}", key.trim()));
                continue;
            }
            out.push(raw.to_string());
        }
    }

    // Append managed keys that weren't already present, in declared order.
    let leftover: Vec<&(String, String)> = updates
        .iter()
        .filter(|(k, _)| pending.contains_key(k.as_str()))
        .collect();
    if !leftover.is_empty() {
        if out.last().map(|l| !l.is_empty()).unwrap_or(false) {
            out.push(String::new());
        }
        if had_content {
            out.push(format!("# Set by `lethe init` on {stamp}"));
        }
        for (k, v) in leftover {
            out.push(format!("{k}={v}"));
        }
    }

    let mut body = out.join("\n");
    if !body.ends_with('\n') {
        body.push('\n');
    }
    std::fs::write(path, &body).with_context(|| format!("writing {}", path.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_env() -> (tempfile::TempDir, std::path::PathBuf) {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("config").join(".env");
        (tmp, path)
    }

    #[test]
    fn upsert_creates_file_with_header_when_absent() {
        let (_tmp, path) = temp_env();
        upsert_env(
            &path,
            &[
                ("LLM_PROVIDER".into(), "openrouter".into()),
                ("LLM_MODEL".into(), "x".into()),
            ],
        )
        .unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("generated by `lethe init`"));
        assert!(body.contains("\nLLM_PROVIDER=openrouter\n"));
        assert!(body.contains("\nLLM_MODEL=x\n"));
    }

    #[test]
    fn upsert_preserves_unmanaged_keys_and_comments() {
        let (_tmp, path) = temp_env();
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(
            &path,
            "# my notes\nEXA_API_KEY=keep-me\nLLM_MODEL=old\nLETHE_API_PORT=9999\n",
        )
        .unwrap();
        upsert_env(
            &path,
            &[
                ("LLM_MODEL".into(), "new".into()),
                ("LLM_PROVIDER".into(), "anthropic".into()),
            ],
        )
        .unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("# my notes"));
        assert!(body.contains("EXA_API_KEY=keep-me"));
        assert!(body.contains("LETHE_API_PORT=9999"));
        assert!(body.contains("\nLLM_MODEL=new\n"));
        assert!(!body.contains("LLM_MODEL=old"));
        assert_eq!(body.matches("LLM_MODEL=").count(), 1);
        assert!(body.contains("\nLLM_PROVIDER=anthropic\n"));
    }
}
